package config

import (
	"io/ioutil"
	"log"

	"github.com/jeremywohl/flatten"
	"gopkg.in/yaml.v2"
)

/// Parse opens, loads and parses a YAML file via path
/// returns a potentially nested Map and a possible error.
func Parse(configPath string) (*map[interface{}]interface{}, error) {
	m := make(map[interface{}]interface{})
	data, err := ioutil.ReadFile(configPath)

	if err != nil {
		return &m, err
	}

	err = yaml.Unmarshal(data, &m)
	if err != nil {
		log.Fatalf("error: %v", err)
	}

	return &m, err
}

/// ParsedConfigToContainerKeys parses the config generated by Parse into key, value pairs for injection into the Container
func ParsedConfigToContainerKeys(parsed map[interface{}]interface{}) (map[string]interface{}, error) {
	return flatten.FlattenString(parsed, "", flatten.DotStyle)
}
